//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseDetails_DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseDetails_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Integrated Authentication.
        /// </summary>
        public static string DatabaseDetails_Integrated {
            get {
                return ResourceManager.GetString("DatabaseDetails_Integrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DatabaseDetails_Password {
            get {
                return ResourceManager.GetString("DatabaseDetails_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string DatabaseDetails_ServerName {
            get {
                return ResourceManager.GetString("DatabaseDetails_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string DatabaseDetails_UserName {
            get {
                return ResourceManager.GetString("DatabaseDetails_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Automatic Graph Layout.
        /// </summary>
        public static string DiagramType_MSAGL {
            get {
                return ResourceManager.GetString("DiagramType_MSAGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio.
        /// </summary>
        public static string DiagramType_Visio {
            get {
                return ResourceManager.GetString("DiagramType_Visio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Settings.
        /// </summary>
        public static string Header_Database {
            get {
                return ResourceManager.GetString("Header_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Type.
        /// </summary>
        public static string Header_DiagramType {
            get {
                return ResourceManager.GetString("Header_DiagramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string Header_Login {
            get {
                return ResourceManager.GetString("Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Level.
        /// </summary>
        public static string Header_ViewLevel {
            get {
                return ResourceManager.GetString("Header_ViewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessViewer - Activity Level View.
        /// </summary>
        public static string MsaglForm_DrawDiagram_ProcessViewer___Activity_Level_View {
            get {
                return ResourceManager.GetString("MsaglForm_DrawDiagram_ProcessViewer___Activity_Level_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessViewer -Task Level View.
        /// </summary>
        public static string MsaglForm_DrawDiagram_ProcessViewer___Task_Level_View {
            get {
                return ResourceManager.GetString("MsaglForm_DrawDiagram_ProcessViewer___Task_Level_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string Options_NoSelection {
            get {
                return ResourceManager.GetString("Options_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grouping by Colour.
        /// </summary>
        public static string OptionsView_Colour {
            get {
                return ResourceManager.GetString("OptionsView_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include unique ID&apos;s.
        /// </summary>
        public static string OptionsView_ID {
            get {
                return ResourceManager.GetString("OptionsView_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Information.
        /// </summary>
        public static string OptionsView_NodeSyle {
            get {
                return ResourceManager.GetString("OptionsView_NodeSyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Connection.
        /// </summary>
        public static string PageDisplayName_Database {
            get {
                return ResourceManager.GetString("PageDisplayName_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Display Mode.
        /// </summary>
        public static string PageDisplayName_LevelType {
            get {
                return ResourceManager.GetString("PageDisplayName_LevelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        public static string PageDisplayName_Options {
            get {
                return ResourceManager.GetString("PageDisplayName_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Processes.
        /// </summary>
        public static string PageDisplayName_Processes {
            get {
                return ResourceManager.GetString("PageDisplayName_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PageDisplayName_Summary {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string PageDisplayName_Welcome {
            get {
                return ResourceManager.GetString("PageDisplayName_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string ProcessView_Header {
            get {
                return ResourceManager.GetString("ProcessView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string ProcessView_Processes {
            get {
                return ResourceManager.GetString("ProcessView_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessViewer 2.0.
        /// </summary>
        public static string ProcessViewerDialogTitle {
            get {
                return ResourceManager.GetString("ProcessViewerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Type.
        /// </summary>
        public static string Summary_GraphType {
            get {
                return ResourceManager.GetString("Summary_GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Summary_Options {
            get {
                return ResourceManager.GetString("Summary_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Summary_Processes {
            get {
                return ResourceManager.GetString("Summary_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Level.
        /// </summary>
        public static string Summary_ViewLevel {
            get {
                return ResourceManager.GetString("Summary_ViewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Button_Cancel {
            get {
                return ResourceManager.GetString("View_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string View_Button_Finish {
            get {
                return ResourceManager.GetString("View_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string View_Button_MoveNext {
            get {
                return ResourceManager.GetString("View_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string View_Button_MovePrevious {
            get {
                return ResourceManager.GetString("View_Button_MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string View_Header_Steps {
            get {
                return ResourceManager.GetString("View_Header_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ViewLevel_Activity {
            get {
                return ResourceManager.GetString("ViewLevel_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubProcess.
        /// </summary>
        public static string ViewLevel_Task {
            get {
                return ResourceManager.GetString("ViewLevel_Task", resourceCulture);
            }
        }
    }
}
