//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.ScheduledTasks.CustomCode.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Architect.ScheduledTasks.CustomCode.Validation.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group&apos;s name cannot be empty..
        /// </summary>
        internal static string GroupNameEmpty {
            get {
                return ResourceManager.GetString("GroupNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName001.
        /// </summary>
        internal static string GroupNameEmptyCode {
            get {
                return ResourceManager.GetString("GroupNameEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group&apos;s name cannot be longer than 50 characters..
        /// </summary>
        internal static string GroupNameLength {
            get {
                return ResourceManager.GetString("GroupNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName002.
        /// </summary>
        internal static string GroupNameLengthCode {
            get {
                return ResourceManager.GetString("GroupNameLengthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date and time must be set to the future..
        /// </summary>
        internal static string STaskDateInvalid {
            get {
                return ResourceManager.GetString("STaskDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STaskDate002.
        /// </summary>
        internal static string STaskDateInvalidCode {
            get {
                return ResourceManager.GetString("STaskDateInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval must be greater than 0..
        /// </summary>
        internal static string STaskIntervalLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("STaskIntervalLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STaskInterval003.
        /// </summary>
        internal static string STaskIntervalLessThanOrEqualToZeroCode {
            get {
                return ResourceManager.GetString("STaskIntervalLessThanOrEqualToZeroCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scheduled task&apos;s name cannot be empty..
        /// </summary>
        internal static string STaskNameEmpty {
            get {
                return ResourceManager.GetString("STaskNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STaskName001.
        /// </summary>
        internal static string STaskNameEmptyErrorCode {
            get {
                return ResourceManager.GetString("STaskNameEmptyErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A task&apos;s name cannot be longer than 50 characters..
        /// </summary>
        internal static string STaskNameLength {
            get {
                return ResourceManager.GetString("STaskNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STaskName004.
        /// </summary>
        internal static string STaskNameLengthCode {
            get {
                return ResourceManager.GetString("STaskNameLengthCode", resourceCulture);
            }
        }
    }
}
