//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Architect.ScheduledTasks
{
	/// <summary>
	/// DomainModel ScheduledTasksDomainModel
	/// Architect Scheduled Tasks
	/// </summary>
	[DslDesign::DisplayNameResource("Architect.ScheduledTasks.ScheduledTasksDomainModel.DisplayName", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Architect.ScheduledTasks.ScheduledTasksDomainModel.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("ff28ec1f-f310-45dd-856e-de127249ab8b")]
	public partial class ScheduledTasksDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// ScheduledTasksDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xff28ec1f, 0xf310, 0x45dd, 0x85, 0x6e, 0xde, 0x12, 0x72, 0x49, 0xab, 0x8b);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public ScheduledTasksDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Group),
				typeof(BaseScheduledTask),
				typeof(CSharpScheduledTask),
				typeof(SqlScheduledTask),
				typeof(GroupHasScheduledTasks),
				typeof(ScheduledTasksDiagram),
				typeof(ScheduledTaskShape),
				typeof(global::Architect.ScheduledTasks.FixUpDiagram),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Group), "GroupName", Group.GroupNameDomainPropertyId, typeof(Group.GroupNamePropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "Name", BaseScheduledTask.NameDomainPropertyId, typeof(BaseScheduledTask.NamePropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "IntervalType", BaseScheduledTask.IntervalTypeDomainPropertyId, typeof(BaseScheduledTask.IntervalTypePropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "Interval", BaseScheduledTask.IntervalDomainPropertyId, typeof(BaseScheduledTask.IntervalPropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "StartDate", BaseScheduledTask.StartDateDomainPropertyId, typeof(BaseScheduledTask.StartDatePropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "Type", BaseScheduledTask.TypeDomainPropertyId, typeof(BaseScheduledTask.TypePropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "DescriptiveInterval", BaseScheduledTask.DescriptiveIntervalDomainPropertyId, typeof(BaseScheduledTask.DescriptiveIntervalPropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "StartDateOnly", BaseScheduledTask.StartDateOnlyDomainPropertyId, typeof(BaseScheduledTask.StartDateOnlyPropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "StartTimeOnly", BaseScheduledTask.StartTimeOnlyDomainPropertyId, typeof(BaseScheduledTask.StartTimeOnlyPropertyHandler)),
				new DomainMemberInfo(typeof(BaseScheduledTask), "TypeDisplay", BaseScheduledTask.TypeDisplayDomainPropertyId, typeof(BaseScheduledTask.TypeDisplayPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(GroupHasScheduledTasks), "Group", GroupHasScheduledTasks.GroupDomainRoleId),
				new DomainRolePlayerInfo(typeof(GroupHasScheduledTasks), "Element", GroupHasScheduledTasks.ElementDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(6);
				createElementMap.Add(typeof(Group), 0);
				createElementMap.Add(typeof(BaseScheduledTask), 1);
				createElementMap.Add(typeof(CSharpScheduledTask), 2);
				createElementMap.Add(typeof(SqlScheduledTask), 3);
				createElementMap.Add(typeof(ScheduledTasksDiagram), 4);
				createElementMap.Add(typeof(ScheduledTaskShape), 5);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Architect.ScheduledTasks.ScheduledTasksDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Group(partition, propertyAssignments);
				case 1: return new BaseScheduledTask(partition, propertyAssignments);
				case 2: return new CSharpScheduledTask(partition, propertyAssignments);
				case 3: return new SqlScheduledTask(partition, propertyAssignments);
				case 4: return new ScheduledTasksDiagram(partition, propertyAssignments);
				case 5: return new ScheduledTaskShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(1);
				createElementLinkMap.Add(typeof(GroupHasScheduledTasks), 0);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Architect.ScheduledTasks.ScheduledTasksDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new GroupHasScheduledTasks(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Architect.ScheduledTasks.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return ScheduledTasksDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (ScheduledTasksDomainModel.resourceManager == null)
				{
					ScheduledTasksDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(ScheduledTasksDomainModel).Assembly);
				}
				return ScheduledTasksDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return ScheduledTasksDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return ScheduledTasksDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ScheduledTasksDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new ScheduledTasksCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					ScheduledTasksDomainModel.copyClosure = copyFilter;
				}
				return ScheduledTasksDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ScheduledTasksDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new ScheduledTasksDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					ScheduledTasksDomainModel.removeClosure = removeFilter;
				}
				return ScheduledTasksDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Architect.ScheduledTasks.FixUpDiagram));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Architect.ScheduledTasks.FixUpDiagram));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ScheduledTasksDeleteClosure : ScheduledTasksDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ScheduledTasksDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ScheduledTasksDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public ScheduledTasksDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Architect.ScheduledTasks.GroupHasScheduledTasks.ElementDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ScheduledTasksCopyClosure : ScheduledTasksCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ScheduledTasksCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ScheduledTasksCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ScheduledTasksCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Architect.ScheduledTasks
{
	/// <summary>
	/// DomainEnumeration: IntervalType
	/// Description for Architect.ScheduledTasks.IntervalType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum IntervalType
	{
		/// <summary>
		/// Years
		/// Description for Architect.ScheduledTasks.IntervalType.Years
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Years.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Years = 0,
		/// <summary>
		/// Months
		/// Description for Architect.ScheduledTasks.IntervalType.Months
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Months.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Months = 1,
		/// <summary>
		/// Weeks
		/// Description for Architect.ScheduledTasks.IntervalType.Weeks
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Weeks.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Weeks = 2,
		/// <summary>
		/// Days
		/// Description for Architect.ScheduledTasks.IntervalType.Days
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Days.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Days = 3,
		/// <summary>
		/// Hours
		/// Description for Architect.ScheduledTasks.IntervalType.Hours
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Hours.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Hours = 4,
		/// <summary>
		/// Minutes
		/// Description for Architect.ScheduledTasks.IntervalType.Minutes
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Minutes.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Minutes = 5,
		/// <summary>
		/// Seconds
		/// Description for Architect.ScheduledTasks.IntervalType.Seconds
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.IntervalType/Seconds.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		Seconds = 6,
	}
}
namespace Architect.ScheduledTasks
{
	/// <summary>
	/// DomainEnumeration: TaskType
	/// Description for Architect.ScheduledTasks.TaskType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TaskType
	{
		/// <summary>
		/// CSharp
		/// Description for Architect.ScheduledTasks.TaskType.CSharp
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.TaskType/CSharp.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		CSharp = 1,
		/// <summary>
		/// SQL
		/// Description for Architect.ScheduledTasks.TaskType.SQL
		/// </summary>
		[DslDesign::DescriptionResource("Architect.ScheduledTasks.TaskType/SQL.Description", typeof(global::Architect.ScheduledTasks.ScheduledTasksDomainModel), "Architect.ScheduledTasks.GeneratedCode.DomainModelResx")]
		SQL = 0,
	}
}

