//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "subprocess";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CloudCore - Architect Sub-Process Designer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Framework One";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CloudCoreArchitectSubProcessDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CloudCoreArchitectSubProcessCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CloudCoreArchitectSubProcessExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CloudCoreArchitectSubProcessCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCloudCoreArchitectSubProcessExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CloudCoreArchitectSubProcessCommandSetId), 0x0001);
	
		// Package identifier
		public const string CloudCoreArchitectSubProcessPackageId = "3a60313d-10af-44d3-b0c1-3cdbef0caa43";
		
		// Editor factory identifier
		public const string CloudCoreArchitectSubProcessEditorFactoryId = "6a850ae9-3487-4c6b-92a0-fbae153565fb";
		
		public const string DefaultDiagramExtension = ".diagram";
		
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Architect
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CloudCoreArchitectSubProcessCommandSetId = "1e34524c-97bb-44ff-a271-2897cefac3d2";
	}
}