//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Architect
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\14.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideStaticToolboxGroup("@Database ActivitiesToolboxTab;Architect.Dsl.dll", "Architect.Database ActivitiesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Architect.Database ActivitiesToolboxTab",
					"@SQLEventToolboxItem;Architect.Dsl.dll", 
					"Architect.SQLEventToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLEvent", 
					"@SQLEventToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Architect.Database ActivitiesToolboxTab",
					"@SQLCostingToolboxItem;Architect.Dsl.dll", 
					"Architect.SQLCostingToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLCosting", 
					"@SQLCostingToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Architect.Database ActivitiesToolboxTab",
					"@SQLBatchStartToolboxItem;Architect.Dsl.dll", 
					"Architect.SQLBatchStartToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLBatchStart", 
					"@SQLBatchStartToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Architect.Database ActivitiesToolboxTab",
					"@SQLParkedToolboxItem;Architect.Dsl.dll", 
					"Architect.SQLParkedToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLParked", 
					"@SQLParkedToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Architect.Database ActivitiesToolboxTab",
					"@SQLBatchWaitToolboxItem;Architect.Dsl.dll", 
					"Architect.SQLBatchWaitToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLBatchWait", 
					"@SQLBatchWaitToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxGroup("@Cloud ActivitiesToolboxTab;Architect.Dsl.dll", "Architect.Cloud ActivitiesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@ClickaltellToolboxItem;Architect.Dsl.dll", 
					"Architect.ClickaltellToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Clickaltell", 
					"@ClickaltellToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@PostageAppToolboxItem;Architect.Dsl.dll", 
					"Architect.PostageAppToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"PostageApp", 
					"@PostageAppToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@CSharpEventToolboxItem;Architect.Dsl.dll", 
					"Architect.CSharpEventToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CSharpEvent", 
					"@CSharpEventToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@CSharpCostingToolboxItem;Architect.Dsl.dll", 
					"Architect.CSharpCostingToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Costing", 
					"@CSharpCostingToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@CSharpBatchStartToolboxItem;Architect.Dsl.dll", 
					"Architect.CSharpBatchStartToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CSharpBatchStart", 
					"@CSharpBatchStartToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@CSharpParkedToolboxItem;Architect.Dsl.dll", 
					"Architect.CSharpParkedToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CSharpParked", 
					"@CSharpParkedToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@CorticonToolboxItem;Architect.Dsl.dll", 
					"Architect.CorticonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Corticon", 
					"@CorticonToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@BatchWaitToolboxItem;Architect.Dsl.dll", 
					"Architect.BatchWaitToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"BatchWait", 
					"@BatchWaitToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("Architect.Cloud ActivitiesToolboxTab",
					"@EmailToolboxItem;Architect.Dsl.dll", 
					"Architect.EmailToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Email", 
					"@EmailToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxGroup("@Process ControlToolboxTab;Architect.Dsl.dll", "Architect.Process ControlToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Architect.Process ControlToolboxTab",
					"@FlowToolboxItem;Architect.Dsl.dll", 
					"Architect.FlowToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Flow", 
					"@FlowToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("Architect.Process ControlToolboxTab",
					"@StopToolboxItem;Architect.Dsl.dll", 
					"Architect.StopToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Stop", 
					"@StopToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("Architect.Process ControlToolboxTab",
					"@SubProcessConnectorToolboxItem;Architect.Dsl.dll", 
					"Architect.SubProcessConnectorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SubProcess", 
					"@SubProcessConnectorToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideStaticToolboxItem("Architect.Process ControlToolboxTab",
					"@WorkflowRuleToolboxItem;Architect.Dsl.dll", 
					"Architect.WorkflowRuleToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"WorkflowRule", 
					"@WorkflowRuleToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 17)]
	[VSShell::ProvideStaticToolboxGroup("@User ActivitiesToolboxTab;Architect.Dsl.dll", "Architect.User ActivitiesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Architect.User ActivitiesToolboxTab",
					"@CloudcoreUserActivityToolboxItem;Architect.Dsl.dll", 
					"Architect.CloudcoreUserActivityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CloudcoreUserActivity", 
					"@CloudcoreUserActivityToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 18)]
	[VSShell::ProvideStaticToolboxItem("Architect.User ActivitiesToolboxTab",
					"@CustomUserActivityToolboxItem;Architect.Dsl.dll", 
					"Architect.CustomUserActivityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CustomUserActivity", 
					"@CustomUserActivityToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 19)]
	[VSShell::ProvideStaticToolboxItem("Architect.User ActivitiesToolboxTab",
					"@MobileUserActivityToolboxItem;Architect.Dsl.dll", 
					"Architect.MobileUserActivityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"MobileUserActivity", 
					"@MobileUserActivityToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 20)]
	[VSShell::ProvideStaticToolboxItem("Architect.User ActivitiesToolboxTab",
					"@HybridUserActivityToolboxItem;Architect.Dsl.dll", 
					"Architect.HybridUserActivityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"HybridUserActivity", 
					"@HybridUserActivityToolboxBitmap;Architect.Dsl.dll", 
					0xff00ff,
					Index = 21)]
	[VSShell::ProvideEditorFactory(typeof(CloudCoreArchitectSubProcessEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(CloudCoreArchitectSubProcessEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(CloudCoreArchitectSubProcessEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"CloudCoreArchitectSubProcess", typeof(CloudCoreArchitectSubProcessEditorFactory))]

	internal abstract partial class CloudCoreArchitectSubProcessPackageBase : DslShell::ModelingPackage
	{
		protected global::Architect.CloudCoreArchitectSubProcessToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new CloudCoreArchitectSubProcessEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Architect.CloudCoreArchitectSubProcessToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			CloudCoreArchitectSubProcessCommandSet commandSet = new CloudCoreArchitectSubProcessCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			CloudCoreArchitectSubProcessClipboardCommandSet clipboardCommandSet = new CloudCoreArchitectSubProcessClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Architect
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 7)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Architect.CloudCoreArchitectSubProcessDirectiveProcessor), global::Architect.CloudCoreArchitectSubProcessDirectiveProcessor.CloudCoreArchitectSubProcessDirectiveProcessorName, "A directive processor that provides access to CloudCoreArchitectSubProcess files")]
	[global::System.Runtime.InteropServices.Guid(Constants.CloudCoreArchitectSubProcessPackageId)]
	internal sealed partial class CloudCoreArchitectSubProcessPackage : CloudCoreArchitectSubProcessPackageBase
	{
	}
}