//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.ScheduledTasks
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "stask";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"ScheduledTasks";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Architect";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ScheduledTasksDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ScheduledTasksCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ScheduledTasksExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ScheduledTasksCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewScheduledTasksExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ScheduledTasksCommandSetId), 0x0001);
	
		// Package identifier
		public const string ScheduledTasksPackageId = "5a65e48f-af3b-49a1-930d-c3ba417cd25f";
		
		// Editor factory identifier
		public const string ScheduledTasksEditorFactoryId = "e18c1e7a-1349-4909-be19-0dff3fe665fe";
		
		public const string DefaultDiagramExtension = ".diagram";
		
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Architect.ScheduledTasks
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ScheduledTasksCommandSetId = "00ad6fdb-506f-49e7-92fc-c0619cf41597";
	}
}