//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.CustomCode.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Architect.CustomCode.Validation.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have at least one child item.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name cannot be empty.
        /// </summary>
        internal static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one startable activity that is set to startable in a flow..
        /// </summary>
        internal static string OneStartableActivityMustBeSet {
            get {
                return ResourceManager.GetString("OneStartableActivityMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current flow continues from another subprocess and therefore does not require an activity set to startable, but if you want to start this sub process on it&apos;s own it will require an activity to be startable.
        /// </summary>
        internal static string OneStartableActivityShouldBeSet {
            get {
                return ResourceManager.GetString("OneStartableActivityShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page does not exist for activity &quot;{0}&quot; in task &quot;{1}&quot;.
        /// </summary>
        internal static string PageNotExist {
            get {
                return ResourceManager.GetString("PageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process does not exist. Re-link subprocess to a process file.
        /// </summary>
        internal static string ProcessNotExist {
            get {
                return ResourceManager.GetString("ProcessNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL file does not exist for activity &quot;{0}&quot; in task &quot;{1}&quot;.
        /// </summary>
        internal static string SQLNotExist {
            get {
                return ResourceManager.GetString("SQLNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All activities must have at least one inflow and one outflow.
        /// </summary>
        internal static string ValidateAllFlow {
            get {
                return ResourceManager.GetString("ValidateAllFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All FromProcessConnectors must have an outflow..
        /// </summary>
        internal static string ValidateFlowFromProcessConnector {
            get {
                return ResourceManager.GetString("ValidateFlowFromProcessConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} type activity must have an inflow.
        /// </summary>
        internal static string ValidateInFlow {
            get {
                return ResourceManager.GetString("ValidateInFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ToProcessConnectors must have one inflow..
        /// </summary>
        internal static string ValidateInFlowToProcessConnector {
            get {
                return ResourceManager.GetString("ValidateInFlowToProcessConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} type activity must have an outflow.
        /// </summary>
        internal static string ValidateOutFlow {
            get {
                return ResourceManager.GetString("ValidateOutFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ToProcessConnectors must have a Sub-process activity reference set..
        /// </summary>
        internal static string ValidateSubProcessActivityHasSubProcessActivityRef {
            get {
                return ResourceManager.GetString("ValidateSubProcessActivityHasSubProcessActivityRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specifiy your sub process name before you create the reference to the process overview.
        /// </summary>
        internal static string ValidateSubProcessNameExistsBeforeReference {
            get {
                return ResourceManager.GetString("ValidateSubProcessNameExistsBeforeReference", resourceCulture);
            }
        }
    }
}
